In [2]:
#1D array
import numpy as np
arr=np.array([1,2,3])
print(arr)
arr.shape

[1 2 3]


(3,)

In [9]:
#2D array
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
arr_2d.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [11]:
#creation of array with arrange method
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
#array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
#linspace(shows elements between the range given at equal distance)
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [24]:
np.linspace(0,21,7)

array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5, 21. ])

In [28]:
#array reshape from 1D to 2D
arr_1d=np.arange(8)
print(arr_1d)
arr_2d=arr_1d.reshape(2,4)
print(arr_2d)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [32]:
# generate two 2D array from 1d array
arr_3d=arr_1d.reshape(2,2,2)
print(arr_3d)
print(arr_3d.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
(2, 2, 2)


In [34]:
#3D/2D array back to 1D array
arr=arr_3d.ravel()
print(arr)
arr1=arr_2d.ravel()
print(arr1)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]


In [39]:
#Indexing
arr=np.arange(20,30)
arr
arr[-1]
#slice object
slice_obj=slice(1,10)
print(arr[slice_obj])
print(arr[1:10])

[21 22 23 24 25 26 27 28 29]
[21 22 23 24 25 26 27 28 29]


In [51]:
#Indexing and scicing for multidimentional array
list_obj=[[10,20,30,40],[11,22,33,44],[55,66,77,88],[1,2,3,4]]
arr_md=np.array(list_obj)
print(arr_md)
print(arr_md[0,0])
print(arr_md[0:3,1:3])

[[10 20 30 40]
 [11 22 33 44]
 [55 66 77 88]
 [ 1  2  3  4]]
10
[[20 30]
 [22 33]
 [66 77]]


In [49]:
arr_md[0,0]

11

In [55]:
#array attributes
arr=np.arange(8)
arr.ndim #returns the length of shape: 1 for 1D,2 for 2D, 3 for 3D
arr_3d=arr.reshape(2,2,2)
arr_3d.ndim
arr.itemsize #4 bytes of memory
arr_3d.itemsize

4

In [59]:
arr=np.arange(1)
arr

array([0])

In [68]:
#random value/empty array
np.empty((1,2))

array([[2.12199579e-314, 6.36598737e-314]])

In [79]:
#Read array data from text files
array=np.loadtxt('filex.txt',delimiter='$',skiprows=2,dtype='int8')
print(array)
print(array.itemsize) #8 bytes of elements become 1 byte of element
print(array.dtype) # dtype will show the bits instead of bytes along with data types(int,float)

[[ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]
 [ 8 18 28]
 [ 9 19 29]]
1
int8


In [83]:
#Parameter list of methods
?np.loadtxt

In [89]:
#Parameter list of methods
?np.savetxt

In [91]:
#Export array data to text/csv files
np.savetxt('output.txt',array,delimiter='$',fmt='%d')

In [104]:
#Pandas library
#Creating Series using array/list 
import pandas as pd
ser=pd.Series([11,12,13,14,15,16])
print(ser)
ser[1:5] #indexing/slicing will be same as list,tuple

0    11
1    12
2    13
3    14
4    15
5    16
dtype: int64


1    12
2    13
3    14
4    15
dtype: int64

In [99]:
#Empty series
ser_e=pd.Series()
ser_e

Series([], dtype: float64)

In [103]:
##Creating Series using dictonary
my_dict={'a':12,'b':14,'c':16}
ser=pd.Series(my_dict)
print(ser['a']) # keys will become index 
print(ser)

12
a    12
b    14
c    16
dtype: int64
b    14
c    16
dtype: int64


########DATAFRAME#######################

In [107]:
##Creating a dataframes using list
a=[11,12,13,14]
df=pd.DataFrame(a)
df

0
0  11
1  12
2  13
3  14

In [108]:
##Creating a dataframes using list of dictionaries
a=[{'a':1,'b':2},{'a':23,'b':25},{'a':5,'b':7,'c':34}]
df=pd.DataFrame(a)
df
#NaN is basically Not a Number, which don't allow to fail any arithmatic operations while None will make it fail

a   b     c
0   1   2   NaN
1  23  25   NaN
2   5   7  34.0

In [114]:
##Creating our own indexes
a=[{'a':1,'b':2},{'a':23,'b':25},{'a':5,'b':7,'c':34}]
df=pd.DataFrame(a,index=['First','Second','Third'])
df

a   b     c
First    1   2   NaN
Second  23  25   NaN
Third    5   7  34.0

In [118]:
##Creating a dataframes using dictionaries of list
a={'x':[1,2,3,4],'y':[11,12,13,14]}
df=pd.DataFrame(a)
df

x   y
0  1  11
1  2  12
2  3  13
3  4  14

In [119]:
##Creating a dataframes using dictionaries of tuple and list
a={'x':[1,2,3,4],'y':(11,12,13,14)}
df=pd.DataFrame(a)
df

x   y
0  1  11
1  2  12
2  3  13
3  4  14

In [122]:
##Creating a dataframes using dictionaries of array
import numpy as np
a={'x':np.array([1,2,3,4]),'y':np.array((11,12,13,14))}
df=pd.DataFrame(a,index=['aa','bb','cc','dd'])
df

x   y
aa  1  11
bb  2  12
cc  3  13
dd  4  14

In [156]:
##Creating a dataframes using dictionaries of series
#Index can not be assigned for Series
import numpy as np
a={'x':pd.Series([1,2,3,4]),'y':pd.Series((11,12,13,14))}
df=pd.DataFrame(a,index=['aa','bb','cc','dd'])
#df=pd.DataFrame(a)
df

x   y
aa NaN NaN
bb NaN NaN
cc NaN NaN
dd NaN NaN

In [127]:
#adding a new column in DataFrame
df['New_Col']=[77,88,99,109]
df

x   y  New_Col
0  1  11       77
1  2  12       88
2  3  13       99
3  4  14      109

In [128]:
#deleting a column in DataFrame
del df['New_Col']
df

x   y
0  1  11
1  2  12
2  3  13
3  4  14

In [132]:
#Accessing a column
df['x']

0    1
1    2
2    3
3    4
Name: x, dtype: int64

In [ ]:
#Each column & row of DataFrame is basically a Series

In [139]:
#Accessing a row using loc & iloc method for Dataframe
#df.loc[row_label] #user defined row lable
#df.iloc[ro_position] # actual row position starting from top as 0

import numpy as np
a={'x':np.array([1,2,3,4]),'y':np.array((11,12,13,14))}
df=pd.DataFrame(a,index=['aa','bb','cc','dd'])
print(df)
series=df.loc['aa']
type(series)
ser_pos=df.iloc[1]
ser_pos

    x   y
aa  1  11
bb  2  12
cc  3  13
dd  4  14


x     2
y    12
Name: bb, dtype: int32

In [150]:
#Accessing a column using loc & iloc method for Dataframe
a={'x':np.array([1,2,3,4]),'y':np.array((11,12,13,14)),'z':np.array((11,12,13,14))}
df=pd.DataFrame(a,index=['aa','bb','cc','dd'])
print(df)
ser1=df.iloc[:,1]
ser2=df.iloc[:,1:3]
ser3=df.iloc[0:3,1:3]
ser3
#accessing multiple colums using label
df[['x','y','']]

    x   y   z
aa  1  11  11
bb  2  12  12
cc  3  13  13
dd  4  14  14


x   y
aa  1  11
bb  2  12
cc  3  13
dd  4  14

In [160]:
#returns number of rows present in dataframe
len(df)
print(df)
#returns small analysis of data present in dataframes
df.describe()

    x   y   z
aa  1  11  11
bb  2  12  12
cc  3  13  13
dd  4  14  14


x          y          z
count  4.000000   4.000000   4.000000
mean   2.500000  12.500000  12.500000
std    1.290994   1.290994   1.290994
min    1.000000  11.000000  11.000000
25%    1.750000  11.750000  11.750000
50%    2.500000  12.500000  12.500000
75%    3.250000  13.250000  13.250000
max    4.000000  14.000000  14.000000

In [173]:
#Add and delete rows
a={'x':pd.Series([4,3,1,2],index=('a','b','c','d')),'y':pd.Series((11,12,13,14),index=('a','b','c','d')),'z':pd.Series((11,12,13,14),index=('a','b','c','d'))}
df1=pd.DataFrame(a)
df1

x   y   z
a  4  11  11
b  3  12  12
c  1  13  13
d  2  14  14

In [169]:
b={'y':pd.Series((11,12,13),index=('0','1','2')),'z':pd.Series((11,12,13,14),index=('0','1','2','3'))}
df2=pd.DataFrame(b)
df2

y   z
0  11.0  11
1  12.0  12
2  13.0  13
3   NaN  14

In [174]:
df1.append(df2,sort=False)

x     y   z
a  4.0  11.0  11
b  3.0  12.0  12
c  1.0  13.0  13
d  2.0  14.0  14
0  NaN  11.0  11
1  NaN  12.0  12
2  NaN  13.0  13
3  NaN   NaN  14

In [175]:
#append rows from one dataframe to another dataframe
df1.append(df2,sort=True)

x     y   z
a  4.0  11.0  11
b  3.0  12.0  12
c  1.0  13.0  13
d  2.0  14.0  14
0  NaN  11.0  11
1  NaN  12.0  12
2  NaN  13.0  13
3  NaN   NaN  14

In [180]:
#drop a column
df1
df3=df1.drop('x',axis=1)
df3

y   z
a  11  11
b  12  12
c  13  13
d  14  14

In [185]:
#drop a row
df1
df4=df1.drop('c',axis=0)
df4

x   y   z
a  4  11  11
b  3  12  12
d  2  14  14

In [208]:
#reading csv/excel file
#file=pd.read_csv('C://Users//HP//Desktop//Untitled Folder//FairDealCustomerData.csv')
#file=pd.read_csv('C:/Users/HP/Desktop/Untitled Folder/FairDealCustomerData.csv')
data=pd.read_csv('bank-data.csv')
data.head() #with no arguments it will print by default 5 lines from top excluding header

age          job  marital    y
0   20      student   single  yes
1   32   management   single  yes
2   49   technician  married  yes
3   32  blue-collar  married  yes
4   33   management  married  yes

In [214]:
#showing column specific head & tail values
data['job'].head(-5)
data['job'].tail(-5)
data

0            student
1         management
2         technician
3        blue-collar
4         management
5             admin.
6        blue-collar
7         technician
8         management
9             admin.
10          services
11        management
12          services
13           student
14           student
15        technician
16     self-employed
17        management
18            admin.
19        management
20        technician
21       blue-collar
22        management
23       blue-collar
24       blue-collar
25            admin.
26       blue-collar
27      entrepreneur
28       blue-collar
29      entrepreneur
           ...      
412      blue-collar
413       management
414      blue-collar
415       technician
416      blue-collar
417    self-employed
418         services
419       technician
420      blue-collar
421       technician
422       technician
423       management
424        housemaid
425       technician
426          student
427       management
428       man

In [217]:
#Summary Statastics of Dataframe
data.describe()
#datatypes of each columns
data.dtypes #string types columns are stored as object

age         int64
job        object
marital    object
y          object
dtype: object

In [225]:
data.to_excel('xyz.xlsx')
data.to_csv('abc.csv',index=False)